# Generated by Django 5.2 on 2025-10-08 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('image', models.ImageField(blank=True, default='images/users/avatar-male.png', null=True, upload_to='images/students/')),
                ('occupation', models.CharField(blank=True, choices=[('Business', 'Business'), ('Service', 'Service'), ('Student', 'Student')], max_length=20)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('facebook', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('name_bn', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('expertise', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('image', models.ImageField(blank=True, default='images/users/avatar-male.png', null=True, upload_to='images/teachers/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Teachers',
            },
        ),
    ]
