# Generated by Django 5.2 on 2025-10-08 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Purpose (English)')),
                ('name_bn', models.CharField(max_length=100, verbose_name='Purpose (Bangla)')),
            ],
        ),
        migrations.CreateModel(
            name='Sadaqah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('sadaqah', 'সাদাকাহ'), ('zakat', 'যাকাত')], default='sadaqah', max_length=10)),
                ('object', models.PositiveIntegerField()),
                ('txn_id', models.CharField(help_text='Transaction ID / Mobile No / Bank Account', max_length=150)),
                ('received', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purpose', to='sadaqah.purpose')),
            ],
        ),
    ]
