# Generated by Django 5.2 on 2025-10-08 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('short_desc', models.TextField()),
                ('description', models.TextField()),
                ('specialty', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/courses/')),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.category')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DecimalField(decimal_places=0, max_digits=3)),
                ('session', models.DecimalField(decimal_places=0, max_digits=2)),
                ('enrollment', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tuition', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gender', models.CharField(blank=True, max_length=255)),
                ('format', models.CharField(blank=True, max_length=100)),
                ('opportunity', models.CharField(blank=True, max_length=255)),
                ('guidance', models.CharField(blank=True, max_length=255)),
                ('revision', models.CharField(blank=True, max_length=255)),
                ('support', models.CharField(blank=True, max_length=255)),
                ('resources', models.CharField(blank=True, max_length=255)),
                ('certificate', models.CharField(blank=True, max_length=255)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='courses.course')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video', models.URLField(blank=True, null=True)),
                ('sheet', models.FileField(blank=True, null=True, upload_to='lessons/sheets/')),
                ('content', models.TextField(blank=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
